<a href="https://colab.research.google.com/github/zuhayerror3i8/AI-ML-Expert-With-Phitron-Batch-01/blob/main/000%20Python%20For%20ML/012_Module_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Module 10 — Data Analysis with Numpy

In [ ]:
# <--- ndarrays in Python --->
import numpy as np

arr1 = np.array([1, 2, 3])    # Create a 1D array

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])  # Create a 2D array

arr3 = np.array([[[1, 2],
                  [3, 4]],

                 [[5, 6],
                  [7, 8]]])   # Create a 3D array

In [ ]:
# <--- ndarray attributes in Python --->

# Dimensions
print(arr1.ndim)   # Output: 1
print(arr2.ndim)   # Output: 2
print(arr3.ndim)   # Output: 3

# Shape
print(arr1.shape)  # Output: (3,)
print(arr2.shape)  # Output: (2, 3)
print(arr3.shape)  # Output: (2, 2, 2)


# Data type
print(arr1.dtype)  # Output: int64 (or int32 depending on the system)
print(arr2.dtype)  # Output: int64 (or int32 depending on the system)
print(arr3.dtype)  # Output: int64 (or int32 depending on the system)

# Size (number of elements)
print(arr1.size)   # Output: 3
print(arr2.size)   # Output: 6
print(arr3.size)   # Output: 8

In [ ]:
# <--- ndarray Data Types in Python --->
arr = np.array([1, 2, 3])
print(arr.dtype)  # Output: int64

arr_float = np.array([1.0, 2.0, 3.0])
print(arr_float.dtype)  # Output: float64

arr_both = np.array([1, 2.0, 3])  # Upcasting to float
print(arr_both.dtype)  # Output: float64

arr_mixed = np.array([1, 2, 3.3, 'X'])  # Upcasting to string
print(arr_mixed.dtype)  # Output: <U32 (or similar string type)

In [ ]:
# <--- Selecting a Data Type for an Array in Python --->
arr = np.array([1, 2, 3], dtype=np.int8)  # Specify int8 data type
print(arr.dtype)  # Output: int8
arr = arr.astype(np.float64)  # Convert to float64
print(arr.dtype)  # Output: float64

In [ ]:
# <--- ndarray creation from existing data in Python --->
lst = [1, 2, 3, 4, 5]
arr_from_list = np.array(lst)  # Create ndarray from list
print(arr_from_list)  # Output: [1 2 3 4 5]
print(type(arr_from_list))  # Output: <class 'numpy.ndarray'>
print(arr_from_list.dtype)  # Output: int64 (or int32 depending on the system)

mixed_lst = [1, 2.0, 3, 'X']
arr_from_mixed_list = np.array(mixed_lst)  # Create ndarray from mixed list
print(arr_from_mixed_list)  # Output: ['1' '2.0' '3' 'X']
print(type(arr_from_mixed_list))  # Output: <class 'numpy.ndarray'>
print(arr_from_mixed_list.dtype)  # Output: <U32

matrix = [[1, 2, 3],
          [4, 5, 6]]
arr_from_matrix = np.array(matrix)  # Create ndarray from matrix
print(arr_from_matrix)  # Output: [[1 2 3] [4 5 6]]
print(type(arr_from_matrix))  # Output: <class 'numpy.ndarray'>
print(arr_from_matrix.dtype)  # Output: int64 (or int32 depending on the system)
print(arr_from_matrix.shape)  # Output: (2, 3)
print(arr_from_matrix.ndim)  # Output: 2

tuple_data = (1, 2, 3, 4, 5)
arr_from_tuple = np.array(tuple_data)  # Create ndarray from tuple
print(arr_from_tuple)  # Output: [1 2 3 4 5]
print(type(arr_from_tuple))  # Output: <class 'numpy.ndarray'>
print(arr_from_tuple.dtype)  # Output: int64 (or int32 depending on the system)
print(arr_from_tuple.shape)  # Output: (5,)
print(arr_from_tuple.ndim)  # Output: 1

set_data = {1, 2, 3, 4, 5}
arr_from_set = np.array(list(set_data))  # Create ndarray from set
print(arr_from_set)  # Output: [1 2 3 4 5]
print(type(arr_from_set))  # Output: <class 'numpy.ndarray'>
print(arr_from_set.dtype)  # Output: int64 (or int32 depending on the system)
print(arr_from_set.shape)  # Output: (5,)
print(arr_from_set.ndim)  # Output: 1

dict_data = {'a': 1, 'b': 2, 'c': 3}
keys = dict_data.keys()  # Get dict keys
values = dict_data.values()  # Get dict values
items = dict_data.items()  # Get dict items
arr_from_keys = np.array(list(keys))  # Create ndarray from dict keys
arr_from_values = np.array(list(values))  # Create ndarray from dict values
arr_from_items = np.array(list(items))  # Create ndarray from dict items
print(arr_from_keys)  # Output: ['a' 'b' 'c']
print(arr_from_values)  # Output: [1 2 3]
print(arr_from_items)  # Output: [['a', 1] ['b', 2] ['c', 3]]
print(type(arr_from_keys))  # Output: <class 'numpy.ndarray'>
print(type(arr_from_values))  # Output: <class 'numpy.ndarray'>
print(type(arr_from_items))  # Output: <class 'numpy.ndarray'>
print(arr_from_keys.dtype)  # Output: <U1 (or similar string type)
print(arr_from_values.dtype)  # Output: int64 (or int32 depending on the system)
print(arr_from_items.dtype)  # Output: <U21 (or similar string type)
print(arr_from_keys.shape)  # Output: (3,)
print(arr_from_values.shape)  # Output: (3,)
print(arr_from_items.shape)  # Output: (3, 2)
print(arr_from_keys.ndim)  # Output: 1
print(arr_from_values.ndim)  # Output: 1
print(arr_from_items.ndim)  # Output: 2
print(arr_from_keys.size)  # Output: 3
print(arr_from_values.size)  # Output: 3
print(arr_from_items.size)  # Output: 6

In [ ]:
# <--- Creating ndarrays from scratch in Python --->
zeros_arr = np.zeros((2, 3))  # Create a 2x3 array of zeros
print(zeros_arr)
print(type(zeros_arr))  # Output: <class 'numpy.ndarray'>
print(zeros_arr.dtype)  # Output: float64
print(zeros_arr.shape)  # Output: (2, 3)
print(zeros_arr.ndim)   # Output: 2
print(zeros_arr.size)   # Output: 6

arr_zeros_like = np.zeros_like(arr3)  # Create an array of zeros with the same shape as arr3
print(arr_zeros_like)
print(arr_zeros_like.shape)           # Output: (2, 2, 2)

ones_arr = np.ones((3, 4))  # Create a 3x4 array of ones
print(ones_arr)
print(type(ones_arr))  # Output: <class 'numpy.ndarray'>
print(ones_arr.dtype)  # Output: float64
print(ones_arr.shape)  # Output: (3, 4)
print(ones_arr.ndim)   # Output: 2
print(ones_arr.size)   # Output: 12

arr_ones_like = np.ones_like(arr3)  # Create an array of ones with the same shape as arr3
print(arr_ones_like)
print(arr_ones_like.shape)          # Output: (2, 2, 2)

empty_arr = np.empty((2, 3))  # Create a 2x3 array without initializing entries
print(empty_arr)
print(type(empty_arr))  # Output: <class 'numpy.ndarray'>
print(empty_arr.dtype)  # Output: float64
print(empty_arr.shape)  # Output: (2, 3)
print(empty_arr.ndim)   # Output: 2
print(empty_arr.size)   # Output: 6

arr_empty_like = np.empty_like(arr3)  # Create an uninitialized array with the same shape as arr3
print(arr_empty_like)
print(arr_empty_like.shape)           # Output: (2, 2, 2)

full_arr = np.full((2, 3), 7)  # Create a 2x3 array filled with the value 7
print(full_arr)
print(type(full_arr))  # Output: <class 'numpy.ndarray'>
print(full_arr.dtype)  # Output: int64
print(full_arr.shape)  # Output: (2, 3)
print(full_arr.ndim)   # Output: 2
print(full_arr.size)   # Output: 6

arr_full_like = np.full_like(arr3, 9)  # Create an array filled with 9 with the same shape as arr3
print(arr_full_like)
print(arr_full_like.shape)             # Output: (2, 2, 2)

In [ ]:
# <--- Array creation with random values in Python --->
rand_arr = np.random.rand(2, 3)  # Create a 2x3 array with random values in [0.0, 1.0)
print(rand_arr)
print(type(rand_arr))  # Output: <class 'numpy.ndarray'>
print(rand_arr.dtype)  # Output: float64
print(rand_arr.shape)  # Output: (2, 3)
print(rand_arr.ndim)   # Output: 2
print(rand_arr.size)   # Output: 6

rand_int_arr = np.random.randint(0, 10, size=(2, 3))  # Create a 2x3 array with random integers in [0, 10)
print(rand_int_arr)
print(type(rand_int_arr))  # Output: <class 'numpy.ndarray'>
print(rand_int_arr.dtype)  # Output: int32
print(rand_int_arr.shape)  # Output: (2, 3)
print(rand_int_arr.ndim)   # Output: 2
print(rand_int_arr.size)   # Output: 6

rand_float_arr = np.random.random_sample((2, 3))  # Create a 2x3 array with random floats in [0.0, 1.0)
print(rand_float_arr)
print(type(rand_float_arr))  # Output: <class 'numpy.ndarray'>
print(rand_float_arr.dtype)  # Output: float64
print(rand_float_arr.shape)  # Output: (2, 3)
print(rand_float_arr.ndim)   # Output: 2
print(rand_float_arr.size)   # Output: 6

In [ ]:
# <--- ndarray creation with range function in Python --->

# np.arange(first, end, step)
arr = np.arange(1, 10 , 1)  # Create an array with values from 1 to 9
mat = arr.reshape(3, 3)  # Reshape to 3x3 matrix

print(arr)  # Output: [1 2 3 4 5 6 7 8 9]
print(mat)  # Output: [[1 2 3]
            #          [4 5 6]
            #          [7 8 9]]
print(type(arr))  # Output: <class 'numpy.ndarray'>
print(arr.dtype)  # Output: int64
print(arr.shape)  # Output: (9,)
print(arr.ndim)   # Output: 1
print(arr.size)   # Output: 9

arr = np.linspace(1, 10, 5)  # Create an array with 5 values evenly spaced between 1 and 10
print(arr)  # Output: [ 1.    3.25  5.5   7.75 10.  ]
print(type(arr))  # Output: <class 'numpy.ndarray'>
print(arr.dtype)  # Output: float64
print(arr.shape)  # Output: (5,)
print(arr.ndim)   # Output: 1
print(arr.size)   # Output: 5

arr = np.logspace(1, 100, 4)  # Create an array with 4 values logarithmically spaced between 10^1 and 10^2
print(arr)  # Output: [1.e+001 1.e+034 1.e+067 1.e+100]
print(type(arr))  # Output: <class 'numpy.ndarray'>
print(arr.dtype)  # Output: float64
print(arr.shape)  # Output: (4,)
print(arr.ndim)   # Output: 1
print(arr.size)   # Output: 4

arr = np.logspace(0, 3, 4, base=2)  # Create an array with 4 values logarithmically spaced between 2^0 and 2^32
print(arr)  # Output: [ 1.  2.  4.  8.]
print(type(arr))  # Output: <class 'numpy.ndarray'>
print(arr.dtype)  # Output: float64
print(arr.shape)  # Output: (4,)
print(arr.ndim)   # Output: 1
print(arr.size)   # Output: 4

In [ ]:
# <--- Creation of diagonal and identity matrices in Python --->
diag_arr = np.diag([1, 2, 3, 4])  # Create a diagonal matrix
print(diag_arr)
print(diag_arr.shape)             # Output: (4, 4)

identity_arr = np.eye(4)   # Create a 4x4 identity matrix
print(identity_arr)
print(identity_arr.shape)  # Output: (4, 4)

manipulated_identity_arr =  np.eye(3, 4, 1)  # Create a 3x4 identity matrix with diagonal offset by 1
print(manipulated_identity_arr)
print(manipulated_identity_arr.shape)        # Output: (3, 4)

manipulated_identity_arr =  np.eye(3, 4, -1)  # Create a 3x4 identity matrix with diagonal offset by -1
print(manipulated_identity_arr)
print(manipulated_identity_arr.shape)         # Output: (3, 4)

In [ ]:
# <--- Indexing and Slicing in Python --->
arr1 = np.array([10, 20, 30, 40, 50])  # 1D array
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])        # 2D array

print(arr1[0])      # Output: 10
print(arr1[2])      # Output: 30

print(arr2[0, 0])   # Output: 10
print(arr2[1, 1])   # Output: 50
print(arr2[2, 2])   # Output: 90

# Slicing: arr[start:end:step]
print(arr1[1:4])    # Output: [20 30 40]
print(arr1[:3])     # Output: [10 20 30]
print(arr1[2:])     # Output: [30 40 50]
print(arr1[::2])    # Output: [10 30 50]
print(arr1[::-1])   # Output: [50 40 30 20 10]

print(arr2[0:2, 1:3])    # Output: [[20 30]
                         #          [50 60]]
print(arr2[:, 1])        # Output: [20 50 80]
print(arr2[1, :])        # Output: [40 50 60]
print(arr2[::2, ::2])    # Output: [[10 30]
                         #          [70 90]]
print(arr2[::-1, ::-1])  # Output: [[90 80 70]
                         #          [60 50 40]
                         #          [30 20 10]]

In [ ]:
# <--- Advanced Indexing and Iteration in Python --->
arr1 = np.array([10, 20, 30, 40, 50])  # 1D array

arr1_mod = arr1[1:4]
arr1_mod[0] = 99
print(arr1)        # Output: [10 99 30 40 50]
print(arr1_mod)    # Output: [99 30 40]

arr1_mod = arr1[1:4].copy()
arr1_mod[0] = 11
print(arr1)        # Output: [10 99 30 40 50]
print(arr1_mod)    # Output: [11 30 40]

lst = np.array([10, 20, 30, 40, 50])
values = lst[[0, 2, 4]]  # Advanced indexing to select specific elements
print(values)            # Output: [10 30 50]

arr2 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])  # 2D array
print(arr2[[0, 2], [1, 2]])      # Output: [20 90]
print(arr2[arr2<30])             # Output: [10 20]

arr3 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])  # 2D array
for i in np.nditer(arr3):
    print(i, end=' ')            # Output: 10 20 30 40 50 60 70 80 90